version: '3'
services:
  nginx:
    image: nginx
    volumes:
     - "./nginx/conf/post_logger.conf:/etc/nginx/conf.d/default.conf"
     - "./nginx/conf/nginx.conf:/etc/nginx/nginx.conf"
     - "./nginx/logs:/var/log/nginx"
    ports:
      - "9091:80"
    restart: always
    logging:
      options:
        max-size: '100m'
        max-file: '7'
      driver: json-file
  pushgw:
    image: prom/pushgateway:latest
    ports:
      - "9092:9091"
    volumes:
      - "./pushgw/data:/pushgw"
    command:
      - "--persistence.file=/pushgw/data"
    restart: always
    logging:
      options:
        max-size: '100m'
        max-file: '7'
      driver: json-file
  prometheus-server:
    image: prom/prometheus:v2.9.2
    volumes:
      - ./prometheus-data:/prometheus-data:rw
      - ./prometheus-data/data:/prometheus/data:rw
    command:
      - "--config.file=/prometheus-data/prometheus.yml"
      - "--web.external-url=https://prometheus.local:9090/"
      - "--web.enable-lifecycle"
      - "--query.lookback-delta=10m"
    ports:
      - "9090:9090"
    restart: always
    logging:
      options:
        max-size: '100m'
        max-file: '7'
      driver: json-file